export const icons = [
  "upFilledHover",
  "arrow",
  "upFilled",
  "chatFilled",
  "facebook",
  "hamburger",
  "instagram",
  "linkedin",
  "telegram",
  "twitter",
  "vk",
  "youtube",
  "arrowRightFilled",
] as string[];
